name: Publish to pkg.go.dev

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Verify module
        run: go mod verify

      - name: List package
        run: |
          # Trigger pkg.go.dev to fetch the new version
          GOPROXY=proxy.golang.org go list -m github.com/jbrinkman/ghi@${{ github.event.inputs.version }}